#pragma once
enum ErrorType {
	NO_LEFT_PARENTHESIS,
	NO_RIGHT_PARENTHESIS,
	NO_WHILE_AFTER_DO_STATEMENT,
	NO_SEMICOLON,
	NO_IDENTIFIER,
	NO_IDENTIFIER_IN_STATEMENT,
	NO_EQUAL,
	NO_NUMBER,
	NO_ASSIGNMENT,
	NO_DO,
	NO_END,
	NO_PERIOD,
	UNKOWN_IDENTIFIER,
	REPEAT_IDENTIFIER
};

void ehandler(ErrorType e, int errorLine, char* iName = NULL);